### ISSUE TITLE
Optimizar el consumo energético del sistema

### ISSUE THREAD

**Issue by JDGA1997** [Grupo-PP1-TSIT4-0/Grupo-PP1-TSIT4.0#27]
- ### Analizar el consumo energético del sistema
- ### Implementar estrategias para reducir el consumo (optimización de código, modos de bajo consumo, etc.).
- ### Documentar las optimizaciones realizadas y los resultados obtenidos

**Comment by juanjosearato** [comment]
[Optimizar el consumo energético del sistema #27.docx](https://github.com/user-attachments/files/17297162/Optimizar.el.consumo.energetico.del.sistema.27.docx)
