### ISSUE TITLE
Optimizar la velocidad de comunicación

### ISSUE THREAD

**Issue by JDGA1997** [Grupo-PP1-TSIT4-0/Grupo-PP1-TSIT4.0#28]
- ### Analizar la velocidad de comunicación entre los dispositivos y la nube
- ### Implementar estrategias para mejorar la velocidad (optimización de protocolos, compresión de datos, etc.).
- ### Documentar las optimizaciones realizadas y los resultados obtenidos

**Comment by juanjosearato** [comment]
[Optimizar la velocidad de comunicación #28.docx](https://github.com/user-attachments/files/17296988/Optimizar.la.velocidad.de.comunicacion.28.docx)
