### ISSUE TITLE
Implementar medidas de seguridad

### ISSUE THREAD

**Issue by JDGA1997** [Grupo-PP1-TSIT4-0/Grupo-PP1-TSIT4.0#29]
- ### Implementar autenticación, cifrado de datos y otras medidas de seguridad en el sistema
- ### Documentar las medidas implementadas

**Comment by juanjosearato** [comment]
[Implementar medidas de seguridad #29.docx](https://github.com/user-attachments/files/17296963/Implementar.medidas.de.seguridad.29.docx)
