### ISSUE TITLE
Realizar simulacro de pruebas de seguridad

### ISSUE THREAD

**Issue by JDGA1997** [Grupo-PP1-TSIT4-0/Grupo-PP1-TSIT4.0#30]
- ### Simular ataques comunes (DDoS, MITM) para evaluar la efectividad de las medidas de seguridad.
- ### Documentar los resultados del simulacro y las vulnerabilidades encontradas

**Comment by juanjosearato** [comment]
[Realizar simulacro de pruebas de seguridad #30.docx](https://github.com/user-attachments/files/17296940/Realizar.simulacro.de.pruebas.de.seguridad.30.docx)
