### ISSUE TITLE
Resolver vulnerabilidades de seguridad

### ISSUE THREAD

**Issue by JDGA1997** [Grupo-PP1-TSIT4-0/Grupo-PP1-TSIT4.0#31]
- ### Implementar soluciones para las vulnerabilidades encontradas durante el simulacro
- ###  Documentar las soluciones implementadas

**Comment by juanjosearato** [comment]
[Resolver vulnerabilidades de seguridad #31.docx](https://github.com/user-attachments/files/17296466/Resolver.vulnerabilidades.de.seguridad.31.docx)
