### ISSUE TITLE
Optimización del sistema

### ISSUE THREAD

**Issue by JDGA1997** [Grupo-PP1-TSIT4-0/Grupo-PP1-TSIT4.0#34]
- ### Analizar datos de rendimiento recolectados
- ### Identificar áreas de mejora
- ### Implementar ajustes y optimizaciones necesarias

**Comment by juanjosearato** [comment]
Analizar datos de rendimiento recolectados: los datos recolectados proporcionan la información necesaria para tener un completo conocimiento del estado de las variables medidas 24 horas los 365 días del año. En función de las muestras de datos podemos avanzar a una siguiente etapa de identificación de mejoras para la industria/área de servicio.

Identificar áreas de mejora: habiendo recolectado los datos, procesarlo e identificarlo logramos comprender la necesidad de incorporar equipamiento de refrigeración/calefacción y ventilación para mantener un ambiente propicio para el proceso productivo o de almacenamiento. El objetivo es lograr un ambiente estable y adecuado que puede ser controlado por sensores y activado por actuadores para activar equipamiento necesario para tal fin.

Implementar ajustes y optimizaciones necesarias: los ajustes se pueden llevar a cabo analizando si son suficiente los sensores, si las ubicaciones son las apropiadas y si existe nueva tecnología.
