### ISSUE TITLE
Documentación del Proyecto

### ISSUE THREAD

**Issue by JDGA1997** [Grupo-PP1-TSIT4-0/Grupo-PP1-TSIT4.0#35]
- ### Crear documento de diseño del sistema
- ### Documentar código fuente con comentarios claros
- ### Elaborar guía de configuración de la nube
- ### Redactar manual de usuario

**Comment by juanjosearato** [comment]
El manual de usuario puede ser redactado como: “as is” significa “como es”, es decir, el mapa de los procesos AS IS demuestra la situación actual y la realidad de los procesos organizacionales, con sus errores y aciertos.
